### ISSUE TITLE
Error when trying to run Resimulation

### ISSUE THREAD

**Issue by vartikatewari** [jonathan-laurent/kappa-counterfactuals#1]
Hi Jonathan,
I work in causality and am trying to use kappa resimulation algorithm to see how counterfactuals perform on real complex biological systems. 
I am unable to get the resimulation running. 

When I try installing I get the following error: 

```
opam pin --dev add KaSim
[ERROR] /Users/vartika/.opam reports a newer OPAM version, aborting.
``` 
So I have installed Kappa using the source. 
I am new to Ocaml , but as I understand I have to compile the resimulation module to use it. But when I try doing that I get the following error. I am using  OCaml version 4.11.1
```
ocamlopt -c resimulation.ml
File "resimulation.ml", line 80, characters 12-30:
80 |     let n = IntCollection.size col in
                 ^^^^^^^^^^^^^^^^^^
Error: Unbound module IntCollection
```

**Comment by vartikatewari** [comment]
I managed to install KaSim, but when I do 'make' I end up with the following error. 
```
ocamlfind: Package `KappaLib' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
make: *** [all] Error 10
```

**Comment by jonathan-laurent** [comment]
Hi @vartikatewari , it is nice to know that you are looking into counterfactual resimulation for rule-based models!
The code for resimulation is strongly coupled with the KaSim API, which underwent several changes in the recent years. I am going to try and see if I can update the code and let you know.

**Comment by jonathan-laurent** [comment]
I just updated the code and it should now work with the latest version of KaSim.

Also, I would be happy to have a more thorough conversation about counterfactual resimulation if you are interested in doing research in this area.

**Comment by vartikatewari** [comment]
@jonathan-laurent Thanks for the code update. I am able to install the kappa-library now. But the make test still gives me an error. 

```

vartika@Vartikas-MacBook-Pro kappa-counterfactuals % make test
dune build bin/resimulate.exe
File "lib/resimulation.ml", line 1064, characters 16-30:
1064 |   let counter = Counter.create ~plot_period:(Configuration.DT 1.0)
                       ^^^^^^^^^^^^^^
Error: This function has type
         ?init_t:float ->
         ?init_e:int ->
         ?max_time:float ->
         ?max_event:int ->
         plot_period:Kappa_terms.Configuration.period ->
         Kappa_runtime.Counter.t
       It is applied to too many arguments; maybe you forgot a `;'.
make: *** [all] Error 1
```

**Comment by vartikatewari** [comment]
@jonathan-laurent I would love to have a conversation with you about counterfactual resimulation. Let me know what would be the best way to reach you. I am a PhD student under Prof. Olga Vitek and work on the intersection of Causality and Molecular Biology and am looking to explore kappa-counterfactual as a way of answering counterfactual questions and its advantages over Dynamic systems(like Omega) or Structural Causal Models.

**Comment by jonathan-laurent** [comment]
> But the make test still gives me an error.

Can you try to use the dev version of KaSim?

```
opam pin kappa-library --dev-repo
```

> I would love to have a conversation with you about counterfactual resimulation. 

You can write me an email at jonathan.laurent@cs.cmu.edu and then we can schedule a call.

**Comment by vartikatewari** [comment]
> ```
> opam pin kappa-library --dev-repo
> ```
> 
> 
> >

I tried it. Still getting an error. 
```
opam pin kappa-library --dev-repo

[kappa-library.4.1.0] synchronised from git+https://github.com/Kappa-Dev/KappaTools.git
kappa-library is now pinned to git+https://github.com/Kappa-Dev/KappaTools.git (version 4.1~dev)

The following actions will be performed:
  ↘ downgrade kappa-library 4.1.0 to 4.1~dev*
Do you want to continue? [Y/n] Y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫

⊘ removed   kappa-library.4.1.0
∗ installed kappa-library.4.1~dev
Done.
vartika@Vartikas-MacBook-Pro kappa-counterfactuals %
vartika@Vartikas-MacBook-Pro kappa-counterfactuals % make test
dune build bin/resimulate.exe
cd tests ; KaSim test.ka -var VA 10000 -trace t.json
/bin/sh: KaSim: command not found
make: *** [test] Error 127
```

**Comment by jonathan-laurent** [comment]
You also need to install `kappa-binaries` using opam so that `KaSim` is in your PATH.

**Comment by vartikatewari** [comment]
> You also need to install `kappa-binaries` using opam so that `KaSim` is in your PATH.
After pinning the dev version, it doesn't let me use the kappa-binaries I had installed.
```
The following dependencies couldn't be met:
  - kappa-binaries → kappa-library >= 4.1.0
      not available because the package is pinned to version 4.1~dev

No solution found, exiting
```

**Comment by jonathan-laurent** [comment]
Ok, so what about something like:

```
git clone https://github.com/Kappa-Dev/KappaTools.git
cd KappaTools
opam install .
```

**Comment by vartikatewari** [comment]
Thanks a lot . The 'make test' works now. 
Although I am still unable to run resimulation algorithm. It gives me an error when I try running it. 

```
File "./resimulate.ml", line 14, characters 5-16:
14 | open Kappa_terms
          ^^^^^^^^^^^
Error: Unbound module Kappa_terms
```

**Comment by jonathan-laurent** [comment]
`make test` is supposed to build and run the resimulation algorithm so I am not sure I understand your problem.

What is the command that led to the error above?

**Comment by vartikatewari** [comment]
My apologies I was trying to run it separately. I got it to work now.
